### ISSUE TITLE
add conceptual images to the pivot section 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/R-Data-Wrangling#14]
Would be nice to have the conceputal images of pivoting here as well:

https://www.storybench.org/wp-content/uploads/2019/08/pivot-longer-image.png

(https://www.storybench.org/wp-content/uploads/2019/08/pivot-wider-image.png

**Comment by asteves** [comment]
@Averysaurus Are these public domain?

**Comment by Averysaurus** [comment]
@asteves I believe so, yes.

**Comment by asteves** [comment]
Creative Commons images have been added in the development branch. Closing this issue.
