### ISSUE TITLE
Part1 : narative suggestion 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/R-Data-Wrangling#20]
Around ln 336: consider mentioning, distinguishing subseting from "Data Manipulation" tasks via summarise, mutate, etc. 
eg: " We've been exploring new ways to subset data, find the observations within a dataset that interest us. In the next part of the lesson we'll learn how to perform operations with a split-apply-combine framework.

**Comment by asteves** [comment]
Filtering can be a part of SAC. 

Are you suggesting that it should be clear that filter and select can be part of SAC, but SAC may not necessarily include filtering?

**Comment by Averysaurus** [comment]
Thought it would be helpful to highlight how function calls change outputs. Data frames return variables with attributes of the data, (summarize, count, etc) rather than data itself. @asteves

**Comment by asteves** [comment]
Right now that information comes when the specific functions that lead to change in data frame structure are introduced. 

Closing this for now, but will reopen this for restructuring if needed after this iteration is taught in early February.
