### ISSUE TITLE
Part2: Storing variables in both rows and columns

### ISSUE THREAD

**Issue by CheFusi** [dlab-berkeley/R-Data-Wrangling#43]
The current code: 

{r}
## Step 1 
step_1 <- testing |> 
  pivot_longer(
    # an alternative method for selecting columns
    d1:d7, 
    names_to = "day",
    values_to = "result",
    values_drop_na = TRUE
  )|>
  # remove the d from day and trim any white space
  # VERY USEFUL to avoid merge problems
  mutate(day = as.numeric(str_replace_all(day,"d", ""))|>trimws())
head(step_1)

towards the end, the as.numeric function is overrided(?) by the trimws function. So the 'day' column remains a <chr> type. 
I think it works if as.numeric is used after (such as:)

{r}
## Step 1 
step_1 <- testing |> 
  pivot_longer(
    # an alternative method for selecting columns
    d1:d7, 
    names_to = "day",
    values_to = "result",
    values_drop_na = TRUE
  )|>
  # remove the d from day and trim any white space
  # VERY USEFUL to avoid merge problems
  mutate(day = (str_replace_all(day,"d", ""))|>trimws()|>
           as.numeric())
head(step_1)

**Comment by asteves** [comment]
Minor point for issues. It's helpful to wrap code in the  `<>` command so github doesn't think it's markdown. 

It looks like the problem here is that there's a () mismatch in that line of code.

Will fix.
