### ISSUE TITLE
|> Pipe only in R version 4.1+

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/R-Data-Wrangling#44]
- The `|>` is a base R version of the pipe implemented in version 4.1

- Some participants did not yet download this version of R, and had to instead use `%>%`

**Solution 1**
Add download latest version of R (at least version 4.1) in the README installation instruction.

I noticed participants don’t always follow these prior to the workshops. To supplement we can add installation of the latest version of R to attendee emails.

**Solution 2**
Since `%>%` is part of the tidyverse, it is easier to troubleshoot package installation during a workshop than installing a new version of R.

**Comment by asteves** [comment]
There are two parts here: 

1. What should the D-Lab standard be? 
2. What should we do for individuals who are not on that standard. 

From a maintenance standpoint, it is easier to have as many things in Base-R as possible. For that reason, my view would be to keep the base pipe. That suggests to me that Solution 1 is appropriate. @aculich @pssachdeva thoughts?

Solution 2 is something that instructors could have in their back pocket.

**Comment by aculich** [comment]
Accounting for major and minor version numbers is something we can plan for— both in terms of when we roll out changes that rely on those versions, as well as which versions we no longer directly support in the context of the workshop and require people to use datahub as a means to follow along.

Summer is when we often have time to make substantive changes, Fall is when we have the greatest number of first-time new people to the D-Lab taking our workshops— however they may be in various states/vintages of RStudio installs.

We can also do more in terms of communicating installation instructions, minimum requirements, and ways for people to test their installations before they arrive.

**Comment by seanmperez** [comment]
Hi @asteves I agree with your reasoning, that base R pipes should be the default, with magrittr pipes being a backup option.

I think this also justifies your [PR for R-Data-Visualization](https://github.com/dlab-berkeley/R-Data-Visualization/pull/27), since we now has base R pipes for the other major R workshops, including R-fundamentals and R-Data-Wrangling.
