### ISSUE TITLE
Remove (or move) the Tidy Data section in part 1.

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/R-Data-Wrangling#45]
- I think it makes more sense to start off learning the simple functions, and then move onto long vs wide at the end.

- While I think this concept encapsulates the essence of tidy data, there isn’t scaffolding to give context as to why it’s important.

- Reviewing long vs wide is one of the most complex topics, and we go over it in code at the end of part 1 which is a more appropriate place.

**Comment by asteves** [comment]
I think it makes sense to move and rework, but I do not understand what scaffolding would be required here regarding tidy data as a concept. Could you explain a little more about what you are thinking here?

The nature of data wrangling in this workshop is for all intents and purposes to make a dataset tidy.
