### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by asteves** [dlab-berkeley/R-Data-Wrangling#8]
README currently lists last time course was offered to be 2018. 

README also does not follow general README guidelines.

**Comment by Averysaurus** [comment]
@asteves  Should we R and Rstudio download links to the new README?

**Comment by asteves** [comment]
the former are in the new README. I don't think so for the latter because we don't do it with other D-Lab projects and all the code can be run on DataHub.

**Comment by asteves** [comment]
Fixed in latest pull request #15
